#!/bin/sh

echo "BEGIN post-receive"

WORK_DIR=$(git config --get remote.work.url)
if [ -z $WORK_DIR ];then
    exit 1
elif [ ! -e $WORK_DIR ];then
    exit 2
fi

if [ -e $WORK_DIR/.git ];then
    WORK_GIT_DIR=$WORK_DIR/.git
fi

git --git-dir=$WORK_GIT_DIR fetch
git --git-dir=$WORK_GIT_DIR --work-tree=$WORK_DIR reset --hard origin/HEAD

